src/droppod/models/UserModel.java
package droppod.models;

public class UserModel {
	private int id;
	private String name;
	private String email;
	private int active_status;
	private int account_type;
	
	public UserModel() {
		id = -1;
		name = null;
		email = null;
		active_status = -1;
		account_type = -1;
	}
	
	public UserModel(int id, String name, String email, int active_status, int account_type) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.active_status = active_status;
		this.account_type = account_type;
	}
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	public int getActiveStatus() {
		return active_status;
	}
	
	public void setActiveStatus(int active_status) {
		this.active_status = active_status;
	}
	
	public int getAccountType() {
		return account_type;
	}
	
	public void setAccountType(int account_type) {
		this.account_type = account_type;
	}
	
}

src/droppod/servlets/AddPodcastServlet.java
package droppod.servlets;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;
import com.mysql.jdbc.Statement;
import com.rometools.modules.itunes.FeedInformation;
import com.rometools.rome.feed.module.Module;
import com.rometools.rome.feed.synd.SyndEntry;
import com.rometools.rome.feed.synd.SyndFeed;
import com.rometools.rome.feed.synd.SyndImage;
import com.rometools.rome.io.FeedException;
import com.rometools.rome.io.SyndFeedInput;
import com.rometools.rome.io.XmlReader;
import droppod.models.EpisodeModel;

/**
 * Parses a given URL to determine if it corresponds to a podcast. If so, podcast info is parsed and
 * added to the database if it does not yet exist.
 * 
 * @author Lucas
 *
 */
public class AddPodcastServlet extends HttpServlet {

  private static final long serialVersionUID = 102831973239L;

  public void doPost(HttpServletRequest request, HttpServletResponse response)
      throws ServletException, IOException {

    response.setContentType("text/html");
    response.setCharacterEncoding("UTF-8");
    PrintWriter out = response.getWriter();

    /* Get URL passed in from the form */
    String podcastUrl = request.getParameter("podcasturl");

    /* Set the podcast url in the session */
    HttpSession session = request.getSession(false);
    if (session != null)
      session.setAttribute("podcasturl", podcastUrl);

    URL feedSource = new URL(podcastUrl);
    SyndFeedInput input = new SyndFeedInput();
    SyndFeed feed = null;
    try {
      feed = input.build(new XmlReader(feedSource));
    } catch (IllegalArgumentException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    } catch (FeedException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
      out.print("<p style=\"color:red\">Invalid podcast url</p>");
    }

    Module module = feed.getModule("http://www.itunes.com/dtds/podcast-1.0.dtd");
    FeedInformation feedInfo = (FeedInformation) module;
    String podcastTitle = feed.getTitle();

    // If the iTunes format image is present, use that one
    URL podcastImageLink = feedInfo.getImage();;
    if (podcastImageLink == null) {
      // Otherwise, fallback to the image embedded in the feed
      podcastImageLink = new URL(feed.getImage().getUrl());
    }

    String podcastDescription = feed.getDescription();
    List<SyndEntry> episodes = feed.getEntries();
    Date lastPublished = episodes.get(0).getPublishedDate();
    String podcastUri = feed.getUri();
    if (podcastUri == null) {
      podcastUri = podcastUrl;
    }

    /*
     * Add the podcast to the database if it doesn't yet exist
     */
    Connection conn = null;
    PreparedStatement pstAddPodcast = null;
    PreparedStatement pstAddPodcastInfo = null;
    PreparedStatement pstGetPodcastId = null;
    PreparedStatement pstAddEpisodesInfo = null;
    ResultSet rs = null;
    int success = 0;

    try {

      Context envContext = new InitialContext();
      Context initContext = (Context) envContext.lookup("java:/comp/env");
      DataSource ds = (DataSource) initContext.lookup("jdbc/droppod");
      // DataSource ds = (DataSource)envContext.lookup("java:/comp/env/jdbc/droppod");
      Connection con = ds.getConnection();

      pstAddPodcast = con.prepareStatement(
          "INSERT INTO droppod.podcasts (url, uri, thumbnail_url) VALUES (?, ?, ?)",
          Statement.RETURN_GENERATED_KEYS);

      pstAddPodcast.setString(1, podcastUrl);
      pstAddPodcast.setString(2, podcastUri);
      pstAddPodcast.setString(3, podcastImageLink.toString());
      success = pstAddPodcast.executeUpdate();

      rs = pstAddPodcast.getGeneratedKeys();
      /* Advance the cursor */
      int podcast_id = 0;
      if (rs.next()) {
        podcast_id = rs.getInt(1);
      }

      /* If adding the podcast worked, add the name, description and episodes */
      if (success == 1 && podcast_id != 0) {

        pstAddPodcastInfo = con.prepareStatement("INSERT INTO droppod.podcasts_translations "
            + "(podcast_id, language_code, podcast_name, podcast_description) "
            + "VALUES (?, ?, ?, ?)");
        pstAddPodcastInfo.setInt(1, podcast_id);
        pstAddPodcastInfo.setString(2, "en");
        pstAddPodcastInfo.setString(3, podcastTitle);
        pstAddPodcastInfo.setString(4, podcastDescription);

        pstAddPodcastInfo.executeUpdate();


        /* Loop through each episode and add them to the db */
        pstAddPodcastInfo = con.prepareStatement(
            "INSERT INTO droppod.episodes (url, podcast_id, release_date)" + "VALUES	(?, ?, ?)");

        pstAddEpisodesInfo = con.prepareStatement(
            "INSERT INTO droppod.episodes_translations (episode_id, language_code, episode_name, episode_description) VALUES (LAST_INSERT_ID(), ?, ?, ?)");

        for (SyndEntry ep : episodes) {
          pstAddPodcastInfo.setString(1, ep.getEnclosures().get(0).getUrl());
          pstAddPodcastInfo.setInt(2, podcast_id);
          pstAddPodcastInfo.setTimestamp(3,
              new java.sql.Timestamp(ep.getPublishedDate().getTime()));

          pstAddPodcastInfo.executeUpdate();

          pstAddEpisodesInfo.setString(1, "en");
          pstAddEpisodesInfo.setString(2, ep.getTitle());
          pstAddEpisodesInfo.setString(3, ep.getDescription().getValue());

          pstAddEpisodesInfo.executeUpdate();
        }


      }

    } catch (Exception e) {
      System.out.println(e);
    } finally {
      if (conn != null) {
        try {
          conn.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }
      if (pstAddPodcast != null) {
        try {
          pstAddPodcast.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }
      if (pstAddPodcastInfo != null) {
        try {
          pstAddPodcast.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }
      if (pstAddEpisodesInfo != null) {
        try {
          pstAddPodcast.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }
      if (pstGetPodcastId != null) {
        try {
          pstAddPodcast.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }
    }

    /* Display the podcast info on the page */
    StringBuilder message = new StringBuilder();
    message.append("<p style=\"color:blue\"> Status: " + success + "</p>");
    message.append("<p style=\"color:blue\">" + podcastTitle + "</p>");
    message
        .append("<img src=\"" + podcastImageLink.toString() + "\" height=\"200\" width=\"200\">");
    message.append("<p style=\"color:blue\">" + podcastDescription + "</p>");
    message.append("<p style=\"color:blue\">" + lastPublished.toString() + "</p>");
    request.setAttribute("message", message.toString());
    RequestDispatcher rd = request.getRequestDispatcher("addPodcast.jsp");
    rd.include(request, response);

    out.close();
  }
}

src/droppod/servlets/PopularPodcastsServlet.java
package droppod.servlets;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
// import javax.servlet.*;
import javax.servlet.http.*;
import javax.sql.DataSource;
import droppod.models.PodcastModel;

public class PopularPodcastsServlet extends HttpServlet {

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  public void doGet(HttpServletRequest request, HttpServletResponse response)
      throws IOException, ServletException {
    // Set responses MIME type
    response.setContentType("text/html;charset=UTF-8");

    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ArrayList<PodcastModel> rows = new ArrayList<PodcastModel>();
    int cityId;
    int countryId;
    String languageCode = null;
    String cityName = null;

    try {

      Context envContext = new InitialContext();
      Context initContext = (Context) envContext.lookup("java:/comp/env");
      DataSource ds = (DataSource) initContext.lookup("jdbc/droppod");
      Connection con = ds.getConnection();
      HttpSession session = request.getSession(false);
      String username = session.getAttribute("name").toString();
      String language = session.getAttribute("language").toString().substring(0, 2);

      // pst1 gets user information for finding podcasts in their city
      pst1 = con.prepareStatement(
          "SELECT users.city_id, users.country_id, cities.name, languages.code\r\n"
              + "from droppod.users\r\n"
              + "left join droppod.countries on users.country_id = countries.id\r\n"
              + "left join droppod.cities on users.city_id = cities.id\r\n"
              + "left join droppod.languages on users.language_id = languages.id\r\n"
              + "where users.username = ?");
      pst1.setString(1, username);
      rs1 = pst1.executeQuery();

      rs1.next();
      cityId = rs1.getInt("city_id");
      countryId = rs1.getInt("country_id");
      languageCode = rs1.getString("code");
      // if the user hasnt set their language, the below sql statment will not return results. This
      // if statement checks for null in the database and sets english as default if so
      if (languageCode == null) {
        languageCode = "en";
      }
      cityName = rs1.getString("name");

      // pst finds podcasts close to the user
      pst = con.prepareStatement(
          "SELECT p.id, COUNT(s.user_id) AS numusers, pt.podcast_name, pt.podcast_description, p.rating, p.url, p.thumbnail_url, p.uuid\r\n"
              + "FROM droppod.podcasts AS p\r\n"
              + "LEFT JOIN droppod.subscriptions AS s ON p.id = s.podcast_id\r\n"
              + "RIGHT JOIN droppod.users as u on s.user_id =  u.id\r\n"
              + "RIGHT JOIN droppod.cities as c on u.city_id = c.id\r\n"
              + "RIGHT JOIN droppod.countries as co on u.country_id = co.id\r\n"
              + "LEFT JOIN droppod.podcasts_translations AS pt ON p.id = pt.podcast_id \r\n"
              + "WHERE pt.language_code =?\r\n" + "AND c.id =?\r\n" + "AND co.id =?\r\n"
              + "GROUP BY p.id\r\n" + "ORDER BY numusers DESC");

      pst.setString(1, language);
      pst.setInt(2, cityId);
      pst.setInt(3, countryId);

      rs = pst.executeQuery();

      while (rs.next()) {
        PodcastModel pod = new PodcastModel();
        pod.setUrl(rs.getURL("url"));
        pod.setName(rs.getString("podcast_name"));
        pod.setDescription(rs.getString("podcast_description"));
        pod.setThumbnail_url(rs.getURL("thumbnail_url"));
        pod.setSubscriptions(rs.getInt("numusers"));
        rows.add(pod);
      }

      // set request attribute for number of users
    } catch (SQLException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    } catch (NamingException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    } finally {

    }

    request.setAttribute("search", rows);
    request.setAttribute("area", cityName);
    request.getRequestDispatcher("/popularPodcasts.jsp").forward(request, response);

  }

}

src/droppod/servlets/RecommendedServlet.java
package droppod.servlets;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.RequestDispatcher;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;
import org.json.JSONArray;
import org.json.JSONObject;

public class RecommendedServlet extends HttpServlet {

  private static final long serialVersionUID = 6614114375578034226L;

  protected void doGet(HttpServletRequest request, HttpServletResponse response) {

    HttpSession session = request.getSession(false);
    String language = session.getAttribute("language").toString().substring(0, 2);
    response.setContentType("application/json");

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {

      Context envContext = new InitialContext();
      Context initContext = (Context) envContext.lookup("java:/comp/env");
      DataSource ds = (DataSource) initContext.lookup("jdbc/droppod");
      conn = ds.getConnection();

      pst = conn.prepareStatement(
          "SELECT ps1.podcast_id as podcast_id1, ps2.podcast_id as podcast_id2, count(ps1.user_id) AS Overlap, pt1.podcast_name AS podcast_name1, pt2.podcast_name AS podcast_name2\r\n"
              + "FROM droppod.subscriptions ps1 CROSS JOIN\r\n"
              + "     droppod.subscriptions ps2\r\n" + "     ON ps1.user_id = ps2.user_id and\r\n"
              + "        ps1.podcast_id < ps2.podcast_id\r\n"
              + "LEFT JOIN droppod.podcasts_translations AS pt1 ON ps1.podcast_id = pt1.podcast_id\r\n"
              + "AND pt1.language_code = ?\r\n"
              + "LEFT JOIN droppod.podcasts_translations AS pt2 ON ps2.podcast_id = pt2.podcast_id\r\n"
              + "WHERE pt2.language_code = ?\r\n" + "GROUP BY ps1.podcast_id, ps2.podcast_id;");
      
      pst.setString(1, language);
      pst.setString(2, language);

      rs = pst.executeQuery();

      JSONObject chartData = new JSONObject();

      JSONArray nodes = new JSONArray();
      JSONArray links = new JSONArray();

      Set<String> nodeSet = new HashSet<String>();



      while (rs.next()) {
        JSONObject newLink = new JSONObject();

        nodeSet.add(rs.getString("podcast_name1"));
        nodeSet.add(rs.getString("podcast_name2"));


        newLink.put("source", rs.getString("podcast_name1"));
        newLink.put("target", rs.getString("podcast_name2"));
        newLink.put("value", rs.getString("Overlap"));

        links.put(newLink);
      }
      for (String item : nodeSet) {
        JSONObject newNode = new JSONObject();
        newNode.put("name", item);

        nodes.put(newNode);
      }


      chartData.put("nodes", nodes);
      chartData.put("edges", links);

      PrintWriter out = response.getWriter();
      out.print(chartData);
      out.flush();

    } catch (Exception e) {
      System.out.println(e);
    } finally {
      if (conn != null) {
        try {
          conn.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }
      if (pst != null) {
        try {
          pst.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }

    }

  }

}

WebContent/admin.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<c:set var="language"
	value="${not empty param.language ? param.language : not empty language ? language : pageContext.request.locale}"
	scope="session" />

<fmt:setLocale value="${language}" />
<fmt:bundle basename="app">
	<html lang="${language}">
	<html>
<head>
<!-- Bootstrap CSS -->
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
	integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
	crossorigin="anonymous">
<link rel="stylesheet" href="css/navbar.css">

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Administrative</title>
<link rel='stylesheet prefetch'
	href='http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css'>

</head>
<body>
	<nav class="navbar navbar-dark bg-mint sticky-top flex-md-nowrap p-0">
		<a class="navbar-brand col-sm-2 col-md-1 mr-0">DropPod</a>


		<form class="form-inline my-2 my-lg-0" action="setLanguageServlet"
			method="get">

			<div class="nav-item dropdown" role="group">
				<select class="btn dropdown-toggle btn-outline-dark"
					aria-labelledby="btnGroupDrop1" id="language" name="language"
					onchange="submit()">
					<option class="dropdown-item" value="en"
						${language == 'en' ? 'selected' : ''}>English</option>
					<option class="dropdown-item" value="fr"
						${language == 'fr' ? 'selected' : ''}>Français</option>
				</select>
			</div>

		</form>

		<form class="form-inline w-100 my-2 my-lg-0" action="searchResult"
			method="get">
			<input class="form-control form-control-mint w-100" type="text"
				name="search" placeholder="<fmt:message key="search.search" />"
				aria-label="Search">
		</form>
		<ul class="navbar-nav px-3">
			<li class="nav-item text-nowrap"><a class="nav-link"
				href="${pageContext.request.contextPath}/logout"><fmt:message
						key="welcome.signout" /></a></li>
		</ul>
	</nav>

	<div class="container-fluid">
		<div class="row no-gutter">
			<nav class="col-md-2 sidebar">
				<div class="sidebar-sticky">
					<ul class="nav flex-column">
						<li class="nav-item"><a class="nav-link" href="#"> <span
								data-feather="user"></span> <fmt:message
									key="welcome.signedinas" />: ${sessionScope.name}
						</a></li>
						<li class="nav-item"><a class="nav-link"
							href="${pageContext.request.contextPath}/welcome.jsp"> <span
								data-feather="cast"></span> <fmt:message key="welcome.casts" />
						</a></li>
						<li class="nav-item"><a class="nav-link"
							href="${pageContext.request.contextPath}/following.jsp"> <span
								data-feather="users"></span> <fmt:message
									key="welcome.following" />
						</a></li>
						<li class="nav-item"><a class="nav-link"
							href="${pageContext.request.contextPath}/popularPodcasts"> <span
								data-feather="globe"></span> <fmt:message key="welcome.popular" />
						</a></li>
						<li class="nav-item"><a class="nav-link"
							href="${pageContext.request.contextPath}/addPodcast.jsp"> <span
								data-feather="plus-square"></span> <fmt:message
									key="welcome.addapodcast" />
						</a></li>
						<li class="nav-item"><a class="nav-link"
							href="${pageContext.request.contextPath}/recommended.jsp"> <span
								data-feather="user-check"></span>
							<fmt:message key="welcome.recommended" />
						</a></li>
						<c:if test="${sessionScope.accessLevel == \"1\"}">
							<li class="nav-item"><a class="nav-link active"
								href="${pageContext.request.contextPath}/admin.jsp"> <span
									data-feather="shield"></span> <fmt:message key="welcome.admin" />
							</a></li>
						</c:if>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
		<div class="border-bottom mb-3">
			<h3>
				<fmt:message key="welcome.admin" />
			</h3>
		</div>
		<form action="userSearch" method="post">
			<div class="form-group">
				<input type="text" class="form-control" name="username"
					id="username" placeholder="<fmt:message key="admin.userSearch" />" />
			</div>
			<!--<input type="submit" class="btn btn-success"
				value="<fmt:message key="admin.search" />" /> -->
		</form>
		<c:if test="${not empty user}">
			<div class="col-sm-6">
				<form action="userEdit" method="post">
					<div class="form-group">
						<label for="id"><fmt:message key="admin.ID" /></label> <input
							type="text" class="form-control" value="${user.id}" name="id"
							id="id" readonly>
					</div>
					<div class="form-group">
						<label for="name"><fmt:message key="admin.username" /></label> <input
							type="text" class="form-control" value="${user.name}" id="name"
							readonly>
					</div>
					<div class="form-group">
						<label for="email"><fmt:message key="admin.email" /></label> <input
							type="text" class="form-control" value="${user.email}" id="email"
							readonly>
					</div>
					<div class="form-group">
						<label for="active"><fmt:message key="admin.active" /></label> 
						<select class="form-control" name="account_type_id" id="account_type_id">
							<c:if test="${user.activeStatus == 0}">
							<option value="0">Active</option>
							<option value="1">Disabled</option>
							</c:if>
							<c:if test="${user.activeStatus == 1}">
							<option value="1">Disabled</option>
							<option value="0">Active</option>
							</c:if>
						</select>
					</div>
					<div class="form-group">
						<label for="account_type_id"><fmt:message key="admin.accountlevel" /></label>
						<select class="form-control" name="account_type_id" id="account_type_id">
							<c:if test="${user.accountType == 0}">
							<option value="0">General User</option>
							<option value="1">Admin User</option>
							</c:if>
							<c:if test="${user.accountType == 1}">
							<option value="1">Admin User</option>
							<option value="0">General User</option>
							</c:if>
						</select>
					</div>

					<button type="submit" class="btn btn-info">
						<fmt:message key="admin.save" />
					</button>
				</form>
			</div>
		</c:if>

		<c:if test="${not empty users}">
			<div class="table-responsive">
				<table class="table">
					<tr>
						<th><fmt:message key="admin.ID" /></th>
						<th><fmt:message key="admin.username" /></th>
						<th><fmt:message key="admin.email" /></th>
						<th><fmt:message key="admin.active" /></th>
						<th><fmt:message key="admin.accountlevel" /></th>
						<th><fmt:message key="admin.action" /></th>
					</tr>
					<c:forEach var="user" items="${users}">
						<tr>
							<td>${user.id}</td>
							<td>${user.name}</td>
							<td>${user.email}</td>
							<td><c:if test="${user.activeStatus == 0}">Active</c:if><c:if test="${user.activeStatus == 1}">Disabled</c:if></td>
							<td><c:if test="${user.accountType == 0}">General User</c:if><c:if test="${user.accountType == 1}">Admin User</c:if></td>
							<td>
								<form action="userSearch" method="post"
									style="padding: 0; margin: 0;">
									<input type="hidden" value="${user.id}" name="id" id="id">
									<button type="submit" class="btn btn-info btn-sm">
										<fmt:message key="admin.edit" />
									</button>
								</form>
							</td>
						</tr>
					</c:forEach>
				</table>
			</div>
		</c:if>
	</div>


	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
		crossorigin="anonymous"></script>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
		integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
		crossorigin="anonymous"></script>
	<script
		src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
		integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
		crossorigin="anonymous"></script>
	<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
	<script>
		feather.replace()
	</script>
	<script src="js/welcome.js"></script>
</body>
</body>
</fmt:bundle>
</html>